---
title: "model"
author: "Tao Huang"
date: "`r Sys.Date()`"
output: html_document
---

# Step 1: gage ID
```{r}
st_all_gage<-c("12413370")
input<-paste("../data_prep/prism_df_summer_",st_all_gage,".rds",sep="") # "../data_prep/prism_df_summer_13266000.rds"
PASTA_name<- " "
rinf_RDS<-paste("rinf_",st_all_gage,  "_mean_ST.rds" ,sep="")
```

```{r}
library("dplyr")
# #install.packages('corrplot')
library("corrplot")
library("RColorBrewer")
# install.packages("gbm")
library("gbm")
# # install.packages("caret")
library("caret")
# #install.packages("pdp")
library("pdp")          # model visualization
```

```{r}
daily_df_summer <-readRDS( input )

daily_df_summer

M<-cor( daily_df_summer[,c("ppt..mm.","tmin..degrees.C.","tmean..degrees.C.","tmax..degrees.C."  ,
"tdmean..degrees.C." ,"vpdmin..hPa."     ,  "vpdmax..hPa."   ,           
"X_00010_00001"   ,    "X_00010_00003"   ,    "X_00060_00003"     , "doy")])

M2<-cor( daily_df_summer[,c("ppt..mm.",
"tmean..degrees.C.",

  "vpdmax..hPa."   ,           "X_00010_00003"   ,    "X_00060_00003"     , "doy")])

#M <-cor( daily_df_summer[,c("mean_StreamTemp","log_mean_Q","mean_AirTemperature_C","max_AirTemperature_C","vpdmax","doy")])

M2

corrplot(M, type="upper", order="hclust",col=brewer.pal(n= 6, name="RdYlBu"))
corrplot(M2, type="upper", order="hclust",col=brewer.pal(n= 6, name="RdYlBu"))

#print(summary(daily_df_summer$base ))
#print(summary(daily_df_summer$log_mean_Q))
hist(daily_df_summer$X_00060_00003 )

#air_diff<- (daily_df_summer$mean_AirTemperature_C-daily_df_summer$mean_StreamTemp)
#print(mean( air_diff))
#print(median( air_diff))
#hist(air_diff)

#M_1 <-cor( daily_df_summer[,c("mean_StreamTemp" ,"base","log_mean_Q","mean_AirTemperature_C")])
#M_1
#corrplot(M_1, type="upper", order="hclust",col=brewer.pal(n=8, name="RdYlBu"))
```

# Model: GBM
```{r}
# set seed for generating random data.
set.seed(42)

# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("X_00010_00003","ppt..mm.",
"tmean..degrees.C.",

  "vpdmax..hPa."   ,     "X_00060_00003"     , "doy"
             )

parts = createDataPartition(  daily_df_summer$X_00010_00003  , p = 0.8, list = F)
train = daily_df_summer[parts, variables ]
print(train)
test =  daily_df_summer[-parts, variables  ]

# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
#print(test_y)
```

```{r}
model_gbm = gbm(train$X_00010_00003        ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 200)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
#barplot( rinf$rel.inf , horiz = TRUE, las = 1)
#ggplot(rinf, aes(rel.inf)) + geom_bar()
rinf$max_yr<-max(as.numeric(daily_df_summer$yr))
rinf$min_yr<-min(as.numeric(daily_df_summer$yr))
rinf$site_id<- st_all_gage

rinf$var<- factor(rinf$var, levels=c(  "mean_AirTemperature_C" ,"log_mean_Q"
))

#ggplot( rinf, aes( var , rel.inf ))+  geom_col()+  coord_flip()


ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "Mean Air Temperature (deg C)" ,"log(Mean Streamflow (cfs))"
 ) )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=16))+
  ggtitle( 
    PASTA_name # paste("USGS",st_all_gage)
    )+ylim( c(0,75))

saveRDS(rinf ,file=   rinf_RDS  )
```

```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(0,30)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="GBM")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```
