---
title: "data_prep"
author: "Tao Huang"
date: "`r Sys.Date()`"
output: html_document
---

# Step 1: gage ID
```{r}
st_all_gage<-c("13311000") # 13150430, 12413370, 13311450, 13213000, 13341050, 13139510, 13018300, 13211205
#,13266000, 14219800, 14205350, 12179900
#,13296000, 12398600
#, 13311000, 13340600 , 12305000, 13342500, 13016450, 13092747, 13310800, 13192200,13317660, 12322000, 13341000 (no Q)
#https://waterdata.usgs.gov/monitoring-location/13266000/#parameterCode=00065&period=P7D&showMedian=false

summer=c(6,7,8)

min_days<- 31*length(summer)* ( 1/8)

RDS_all<-paste("prism_df_",st_all_gage,".rds",sep="")

RDS<-paste("prism_df_summer_",st_all_gage,".rds",sep="")

data_for_py <- paste("prism_df_summer_",st_all_gage,".csv",sep="")

startDate <- "2007-10-01"

endDate <- "2023-09-30"

PASTA_name<- st_all_gage #"Groundwater-driven stream (USGS 13266000)"

prism_csv <- paste("PRISM_USGS_",st_all_gage,".csv", sep="")
print(prism_csv)

statCd= c("00001","00003") #00001 max, 00003 mean

```

```{r}
# install.packages("dataRetrieval")
library("dataRetrieval") # for getting USGS NWIS data
#library("grwat")
library("dplyr") # Pipes in R
library("tidyverse")      # data manipulation and visualization
#library("lubridate")      # easily work with dates and times
#library("viridis")
#library("reshape2")
```

# extracts latitude and longitude coordinates of the gage station
```{r}
siteINFO <- dataRetrieval::readNWISsite( st_all_gage )
print(siteINFO)
print(c(siteINFO$dec_lat_va,siteINFO$dec_long_va))
print("https://prism.oregonstate.edu/explorer/")
```

# https://prism.oregonstate.edu/explorer/
```{r}
prism<-read.csv( prism_csv)
prism$Date <-as.Date(prism$Date, format="%Y-%m-%d")
summary(prism)
```

  #00060: Discharge, cubic feet per second
  #00010:	Physical	Temperature, water, degrees Celsius	
```{r}
#create empty tables
meanSummerT_df<-data.frame(
  agency_cd= " ",
  site_no="",
  Date=as.Date("1951-01-01",format="%Y-%m-%d"),
#  X_00010_00001=0,
 # X_00010_00001_cd=0,
  X_00010_00003=0,
  X_00010_00003_cd= "",
 # X_00060_00001=0,    
#  X_00060_00001_cd= "", no max Q
  X_00060_00003=0,    
  X_00060_00003_cd= "",
  yr="",
  mo=0,
waterYear=0
  )
meanSummerT_df
```

```{r}
for (id in st_all_gage) {
  siteNumber <-  id 
  parameterCd <- c("00010","00060") 
  ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29

  meanT <-readNWISdv(siteNumber, parameterCd,startDate, endDate, statCd=  statCd )
  meanT <- addWaterYear(meanT)
  if (dim(meanT )[2]>5){
    meanT$yr<- format(meanT$Date, format = "%Y") 
    meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
    meanSummerT<-meanT[ ,c("agency_cd","site_no","Date"
                         #  ,"X_00010_00001"
                          # ,"X_00010_00001_cd"
                           ,"X_00010_00003"
                           ,"X_00010_00003_cd"
                          # ,"X_00060_00001"
                          # ,"X_00060_00001_cd"
                           ,"X_00060_00003"
                           ,"X_00060_00003_cd"
                           ,"yr","mo" ,"waterYear" )]
    meanSummerT_df <-rbind(meanSummerT_df,meanSummerT)
  }
}

meanSummerT_df
```

```{r}
# is there NA in mean ST or Q?
df<-meanSummerT_df[!is.na(meanSummerT_df$X_00010_00003) &  !meanSummerT_df$mo<1 & !is.na(meanSummerT_df$X_00060_00003 ),]

table(df[df$mo %in%  summer,]$yr)
miss_yr<-data.frame(table(df[df$mo %in%  summer,]$yr))
yrs<-as.numeric(as.character(miss_yr[miss_yr$Freq > min_days,]$Var1))
yrs
df<-df[df$yr %in% yrs,]
summary(df)
```

merge dfs
```{r}

prism_df<-merge(prism,df,by.x="Date",by.y= "Date")

#prism_df$X_00010_00003 -> prism_df$mean_StreamTemp
#prism_df$X_00010_00001 -> prism_df$max_StreamTemp
#log(prism_df$X_00060_00003)->prism_df$log_mean_Q
#prism_df$tmax..degrees.C. ->prism_df$max_AirTemperature_C
#prism_df$tmean..degrees.C.->prism_df$mean_AirTemperature_C
#prism_df$vpdmax..hPa.->prism_df$vpdmax
prism_df$doy<-yday( prism_df$Date )

#prism_df<-prism_df[,c("Date", "yr"
                      #, "vpdmax"                     , "mean_AirTemperature_C" 
                      #, "max_AirTemperature_C","base",  "log_mean_Q", "max_StreamTemp", "mean_StreamTemp","mo","doy")]

prism_df_summer<-prism_df[  prism_df$mo %in%  summer ,]

prism_df_summer<-prism_df_summer[prism_df_summer$X_00010_00003>0,]

summary(prism_df_summer)

```

```{r}
prism_df

boxplot(log(prism_df_summer$X_00060_00003) ~ prism_df_summer$yr)

boxplot(   (prism_df_summer$tmean..degrees.C. - prism_df_summer$X_00010_00003 ) ~ prism_df_summer$yr)

boxplot(   (   prism_df_summer$X_00010_00003/prism_df_summer$tmean..degrees.C. ) ~ prism_df_summer$yr , ylim = c(0, 1), xlab="", ylab="ST/AT", main=  ChoptankInfo$station_nm )

boxplot(   prism_df_summer$tmean..degrees.C.   ~ prism_df_summer$yr)

boxplot(   prism_df_summer$X_00010_00003   ~ prism_df_summer$yr)

```


```{r}
getwd()
saveRDS(prism_df ,RDS_all)
saveRDS(prism_df_summer,RDS)
write.csv(prism_df_summer,data_for_py)
```

# pasta
```{r}
prism_df_positive<-prism_df[ prism_df$tmean..degrees.C. >0,]
lim=c(0, max(prism_df$tmean..degrees.C.)+1 )
plot(prism_df_positive$tmean..degrees.C., prism_df_positive$X_00010_00003, xlim = lim,ylim=lim, col=prism_df_positive$yr )
summary(lm(  prism_df_positive$X_00010_00003 ~ prism_df_positive$tmean..degrees.C.  ))
```

```{r}
prism_df_positive_17_21<- prism_df_positive[prism_df_positive$waterYear %in% c("2017","2021"),]
lim=c(0, max(prism_df$tmean..degrees.C.)+1 )

plot( prism_df_positive_17_21$tmean..degrees.C.,  prism_df_positive_17_21$X_00010_00003, xlim = lim,ylim=lim, col=prism_df_positive_17_21$waterYear )

ggplot(prism_df_positive_17_21, aes(x = tmean..degrees.C. , y =  X_00010_00003, color = waterYear)) +
  geom_point() +
  labs(title = "Scatter Plot with Legend", color = "Group")

summary(lm(   prism_df_positive_17_21$X_00010_00003 ~ prism_df_positive_17_21$tmean..degrees.C.  ))

summary(lm(   prism_df_positive_17_21[prism_df_positive_17_21$waterYear==2017,]$X_00010_00003 ~ prism_df_positive_17_21[prism_df_positive_17_21$waterYear==2017,]$tmean..degrees.C.  ))

summary(lm(   prism_df_positive_17_21[prism_df_positive_17_21$waterYear==2021,]$X_00010_00003 ~ prism_df_positive_17_21[prism_df_positive_17_21$waterYear==2021,]$tmean..degrees.C.  ))

```

```{r}
lim=c(0, max(prism_df_summer$tmean..degrees.C.)+1 )

plot( prism_df_summer$tmean..degrees.C.,  prism_df_summer$X_00010_00003, xlim = lim,ylim=lim, col=prism_df_summer$waterYear )

ggplot(prism_df_summer, aes(x = tmean..degrees.C. , y =  X_00010_00003, color = waterYear)) +
  geom_point() +
  labs(title = "Scatter Plot with Legend", color = "Group")

summary(lm(   prism_df_summer$X_00010_00003 ~ prism_df_summer$tmean..degrees.C.  ))

summary(lm(   prism_df_summer[prism_df_summer$waterYear==2017,]$X_00010_00003 ~ prism_df_summer[prism_df_summer$waterYear==2017,]$tmean..degrees.C.  ))

summary(lm(   prism_df_summer[prism_df_summer$waterYear==2021,]$X_00010_00003 ~ prism_df_summer[prism_df_summer$waterYear==2021,]$tmean..degrees.C.  ))
```

```{r}
diff_2021<- prism_df_summer[prism_df_summer$waterYear==2021,]$tmean..degrees.C.  -prism_df_summer[prism_df_summer$waterYear==2021,]$X_00010_00003
hist(diff_2021)
summary(diff_2021)

diff_2017<- prism_df_summer[prism_df_summer$waterYear==2017,]$tmean..degrees.C.  -prism_df_summer[prism_df_summer$waterYear==2017,]$X_00010_00003
hist(diff_2017)
summary(diff_2017)
```

```{r}

```


# breakpoint analysis for the breakpoint of summer

```{r}
"run"
```

